server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
ingester:
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
