services:
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317 # OTLP gRPC 接口
    networks:
      - otel-network
    depends_on:
    #   - loki
      - tempo
      - prometheus

  # loki:
  #   image: grafana/loki:latest
  #   volumes:
  #     - ./config/loki-config.yaml:/etc/loki/local-config.yaml
  #   ports:
  #     - 3100:3100
  #   networks:
  #     - otel-network

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # tempo
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3080:3000' # Grafana Web UI
    networks:
      - otel-network
    depends_on:
      # - loki
      - tempo
      - prometheus

networks:
  otel-network:
    driver: bridge
